name = "DRIPs"
uuid = "12fec403-b259-46d8-9e74-75aa213074e9"
authors = ["Hassan Afrouzi", "Choongryul Yang", "Miguel Acosta"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test","SafeTestsets"]
