name = "DRIPs"
uuid = "12fec403-b259-46d8-9e74-75aa213074e9"
authors = ["Hassan Afrouzi", "Choongryul Yang", "Miguel Acosta"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
